### ISSUE TITLE
Exit status 128

### ISSUE THREAD

**Issue by gandarez** [gabrie30/ghorg#55] opened 2020-01-07 20:16 UTC
**Describe the bug**
============ Issues ============
Problem trying to clone Repo: https://***.git Error: exit status 128

**To Reproduce**
ghorg clone --scm gitlab --token *** --namespace *** --path F:\GHORG --base-url https://gitlab.***.com/api/v4 --clone-type org ***

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10

**Comment by plastmasser** [comment] 2020-01-17 10:28
same issue on linux mint

**Comment by gabrie30** [comment] 2020-01-28 03:13
what if you add the flag `--protocol=ssh` to clone via ssh do you get the same result?

**Comment by hermes-pimentel** [comment] 2020-01-30 14:13
Same issue on MacOS using protocol ssh or https.

**Comment by gabrie30** [comment] 2020-02-03 04:31
Do you get the same error for every repo in the org, or do some succeed?

**Comment by romancin** [comment] 2020-02-03 16:42
Same problem here. Tried on Deepin, CentOS, macOS...
@gabrie30 only some repos, some are cloned correctly. Cloning them by hand works.

**Comment by hermes-pimentel** [comment] 2020-02-03 17:00
For me, the problem is intermittent, about 10% fail, but is not always the same repos, and sometimes, all work as expected.

**Comment by gabrie30** [comment] 2020-02-04 06:02
What is the default branch of the repos that fail? Is it something other than master?

Or do the repos not have any files?

**Comment by gabrie30** [comment] 2020-02-04 06:04
What version of git are you using?

**Comment by gandarez** [comment] 2020-02-04 15:34
For me git version is
```
git version 2.23.0.windows.1
```

**Comment by gandarez** [comment] 2020-02-04 16:34
Interesting point is that in the console I don't see my token being passed to the url, I might see
```
 https://oauth2:{token}.**.com/some-repo.git
```

**Comment by gabrie30** [comment] 2020-02-04 17:21
I've seen errors like this when 

- repo does not have the branch you try to clone
- repo has no files to clone
- git is on an older version
- there aren't enough file descriptors available (increase ulimits)

@gandarez could you verify the first two points above then try increasing your ulimits...If this does not work

**Comment by gandarez** [comment] 2020-02-04 18:04
@gabrie30 did you see my comments above?

Anyway all the repos have files, they are not too big in terms of number of files, git is up to date and finally the machine is a 64gb of ram.

**Comment by gabrie30** [comment] 2020-02-05 04:56
> The function `getAllOrgCloneUrls` uses the client for the correct `scm` but then you loop over `cloneTargets` and then call the raw `git clone`.
> 
> https://github.com/gabrie30/ghorg/blob/master/cmd/clone.go#L391

I'm not sure I understand why calling git clone in a loop using the repos clone url would be an issue? You don't need to use an SCM's client to clone a repo, you only need the url.

Its essentially running `git clone https://github.com/kubernetes/org.git $HOME/Desktop/kubernetes_ghorg`

How big is the org you are trying to clone?

**Comment by gandarez** [comment] 2020-02-05 16:35
I forked, changed the code but I don't know how to compile Go and run it. Can you briefly explain?

**Comment by gabrie30** [comment] 2020-02-05 19:09
@gandarez awesome! [Do you have your go environment setup?](https://golang.org/doc/install)

1. cd ghorg
2. go get ./...
3. go build (this creates an executable)
4. ./ghorg clone kubernetes (use the executable)

**Comment by gandarez** [comment] 2020-02-06 14:40
I don't know why when calling the local build `(.exe)` it's not actually calling it. To make sure I changed the version into `version.go` and it is still showing the old version. Any thoughts?

**Comment by gabrie30** [comment] 2020-02-06 15:31
> I don't know why when calling the local build `(.exe)` it's not actually calling it. To make sure I changed the version into `version.go` and it is still showing the old version. Any thoughts?

After you changed the version did you re-run `go build`? Also make sure you dont have ghorg installed any other way, not sure if windows has a which cmd but try running `which ghorg` and deleting that just to make sure you aren't calling that instead.

**Comment by gandarez** [comment] 2020-02-06 15:34
I did `go clean` then `go build` to make sure everything was rebuilt. How can I uninstall `ghorg`? I installed using `go get...`.

**Comment by gabrie30** [comment] 2020-02-06 15:37
You might have a binary already created thats in your path, or is somehow being called and not the one you built. It's probably in your go path, so if you run `which ghorg` then just delete that binary it will essentially be uninstalled.

**Comment by gandarez** [comment] 2020-02-06 18:07
I really don't know where the `ghorg` is coming from.

```bash
λ which ghorg
which: no ghorg in ....
```

**Comment by gabrie30** [comment] 2020-02-06 23:17
Thats really strange....Only thing I can think of is you're not working out of your $GOPATH. Make sure you are working out of `$GOPATH/src/github.com/gabrie30/ghorg`

Although this shouldn't really matter if you are calling the built binary.

**Comment by gabrie30** [comment] 2020-02-08 22:55
@gandarez  do you have a gitconfig setup with your email and username?

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

**Comment by gabrie30** [comment] 2020-02-15 20:00
Made some changes on master if anyone having the issue could re-install and try again that would be helpful.

**Comment by biscaldis** [comment] 2020-02-17 11:59
Hi @gabrie30, just built from master but still having the same issue. It now handles repos without the specified branch but other repos are failing with Error 128. All repos have files, none of them is very large, none of them is using LFS. Attached configuration: 
```
*************************************
* SCM      : gitlab
* Type     : org
* Protocol : ssh
* Branch   : dev
* Location : /home/*****/code/test_ghorg/
* Base URL : https://gitlab.*****.com/api/v4
*************************************
```

**Comment by gandarez** [comment] 2020-02-17 14:20
@gabrie30 I think you might consider using the same git client for all operations. As I mentioned before the process use two different clients in the same process which fails for the `clone` operation.

**Comment by gabrie30** [comment] 2020-02-17 16:02
> @gabrie30 I think you might consider using the same git client for all operations. As I mentioned before the process use two different clients in the same process which fails for the `clone` operation.

Thats what I just added. I'm curious if that will fix your clone issue, if it does I was going to use the same client for the rest of the git operations.

**Comment by gandarez** [comment] 2020-02-17 19:49
I ran ` go get -u github.com/gabrie30/ghorg` and it's still version `1.10.0`. So I don't think it get updated.

**Comment by gabrie30** [comment] 2020-02-17 21:10
> I ran ` go get -u github.com/gabrie30/ghorg` and it's still version `1.1.10`. So I don't think it get updated.

I think you got the latest, I just forgot to bump the version.

**Comment by gandarez** [comment] 2020-02-17 21:12
Now has thrown ` Error: authentication required`

**Comment by gabrie30** [comment] 2020-02-18 00:22
> Now has thrown ` Error: authentication required`

Can you tell me a little bit more about this? Does it happen consistently, is the org large, whats the rest of the error? Does `ghorg clone kubernetes` have errors as well? The problem with all these errors is they are not form ghorg, they are originating from git, im guessing as a result of the high concurrency and ghorg is just passing along the error message.

**Comment by gandarez** [comment] 2020-02-18 01:41
I haven't tried cloning `kubernetes` yet. My organization requires authentication which is being passed by the token but in this version seems to have changed a bit the way git works because this is a new error. All the 84 repos have failed with the same error.

**Comment by gabrie30** [comment] 2020-02-18 01:46
> I haven't tried cloning `kubernetes` yet. My organization requires authentication which is being passed by the token but in this version seems to have changed a bit the way git works because this is a new error. All the 84 repos have failed with the same error.

What SCM are you using and is your account setup with two factor authentication?

**Comment by gabrie30** [comment] 2020-02-18 02:29
I've created a branch called `limiting` that limits goroutines to 10 to test this theory. Could you check out this branch do a go install and see if this works? Visually it will be a bit differently than master. You will not see the success/errors grouped together.

**Comment by biscaldis** [comment] 2020-02-26 09:54
I've tested with limiting branch but it seems the issue it's still there. Also, I still see the Success/Info/Issues sections grouped.
I'm on `commit 44f00160f5287fdfd1b78b58a5a91d9087ccd363 (HEAD -> limiting, origin/limiting)`

**Comment by gabrie30** [comment] 2020-02-26 16:57
> I've tested with limiting branch but it seems the issue it's still there. Also, I still see the Success/Info/Issues sections grouped.
> I'm on `commit 44f00160f5287fdfd1b78b58a5a91d9087ccd363 (HEAD -> limiting, origin/limiting)`

It sounds like you are still using the binary built off master. Can you try

- cd $HOME/go/src/github.com/gabrie30/ghorg
- brew uninstall ghorg
- rm $(which ghorg)
- go install
- ghorg clone xxxx

**Comment by biscaldis** [comment] 2020-02-26 17:15
Yeah. You're actually right, I didn't noticed I had a duplicate repo. 
I built with limiting branch and now Exit 128 is not raising anymore. This seems fixed. 
However, it is needed to do a `go get` in order to install **[github.com/korovkin/limiter](https://github.com/korovkin/limiter)**

**Comment by gandarez** [comment] 2020-02-26 19:02
I upgraded to `1.1.11` and then I started getting an error

```
Problem trying to clone Repo: ***.git Error: authentication required
```

**Comment by gabrie30** [comment] 2020-02-29 19:27
> I upgraded to `1.1.11` and then I started getting an error
> 
> ```
> Problem trying to clone Repo: ***.git Error: authentication required
> ```

Can you pull the latest off `limiting` head should be `66b5da3` then try cloning via https. I think this should solve that error.

**Comment by gabrie30** [comment] 2020-02-29 23:10
Likely going to merge this into master and cut a new release this weekend. If anyone else can confirm that would be really helpful! Thanks all 👍

**Comment by gabrie30** [comment] 2020-03-01 20:38
These changes have been merged into master. If you want the latest version 1.2.0 its available to go install or brew install, just make sure you update your ghorg/conf.yaml to include `GHORG_CONCURRENCY:`

Will reopen if anyone is still having issues after installing master

**Closed by gabrie30** 2020-03-01 20:38 UTC

**Comment by gandarez** [comment] 2020-03-02 16:33
@gabrie30 I updated to latest version `1.20` and now it's prompting for password. The username's field comes filled with the token.

![image](https://user-images.githubusercontent.com/782854/75696431-92af9480-5c79-11ea-9e9c-ffb51f198e92.png)
